<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NetGding.Collector</RootNamespace>
    <UserSecretsId>netgding-collector-dev</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NetGding.Contracts\NetGding.Contracts.csproj" />
    <ProjectReference Include="..\..\NetGding.Configurations\NetGding.Configurations.csproj" />
    <ProjectReference Include="..\NetGding.Analyzer\NetGding.Analyzer.csproj" />

  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NetGding.Collector.Tests" />
  </ItemGroup>

</Project>
